image:
  repository: codercom/code-server
  pullPolicy: IfNotPresent
  tag: "latest"

replicas: 1

strategy:
  type: RollingUpdate

securityContext:
  runAsUser: 568
  runAsGroup: 568

env:
  TZ: "America/New_York"
  PASSWORD: "changeme"
  
service:
  enabled: true
  type: ClusterIP
  port:
    name: codeserver
    protocol: TCP
    port: 8080

persistence:
  config:
    enabled: false
    mountPath: /home/coder

ingress:
  enabled: false
