image:
  repository: codercom/code-server
  pullPolicy: IfNotPresent
  tag: "v3.10.0"

controller:
  enabled: true
  replicas: 1

securityContext:
  runAsUser: 568
  runAsGroup: 568

secret:
  PASSWORD: adminadmin

env:
  TZ: "America/New_York"
  
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 8080
        protocol: HTTP

persistence:
  config:
    enabled: false
    mountPath: /home/coder

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
