apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  wg0.conf: |
{{ .Values.configSecret | indent 4 }}