image:
  repository: ghcr.io/jr0dd/heimdalljs
  pullPolicy: IfNotPresent
  tag: "latest"

replicas: 1

strategy:
  type: Recreate

env:
  TZ: "America/New_York"

service:
  enabled: true
  type: ClusterIP
  port:
    name: heimdall
    protocol: HTTP
    port: 3000

persistence:
  config:
    enabled: false
    mountPath: /config

ingress:
  enabled: false

# disabled for testing
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
