image:
  repository: jlesage/mkvtoolnix
  pullPolicy: IfNotPresent
  tag: "latest"

replicas: 1

strategy:
  type: Recreate

env:
  TZ: "America/New_York"
  USER_ID: "568"
  GROUP_ID: "568"
  #SUB_GROUP_IDS: ""
  #UMASK: ""
  KEEP_APP_RUNNING: "1"
  DISPLAY_WIDTH: "2560"
  DISPLAY_HEIGHT: "1440"

service:
  enabled: true
  type: ClusterIP
  #externalTrafficPolicy: Local
  port:
    name: mkvtoolnix
    protocol: TCP
    port: 5800

persistence:
  config:
    enabled: false
    mountPath: /config
  storage:
    enabled: false
    mountPath: /storage

ingress:
  enabled: false

probes:
  startup:
    spec:
      initialDelaySeconds: 30
