image:
  repository: ghcr.io/jr0dd/discord-stock-ticker
  pullPolicy: IfNotPresent
  tag: "v3.3.1"

lifecycle:
  postStart:
    exec:
      command: ["bash", "/app/config.sh"]

controller:
  enabled: true
  replicas: 1
  strategy: RollingUpdate

env:
  TZ: "America/New_York"

service:
  main:
    ports:
      http:
        port: 8080

prometheus:
  serviceMonitor:
    enabled: false
    interval: 10s
    additionalLabels: {}
  prometheusRule:
    enabled: false
    additionalLabels: {}

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["bash", "-c", "if [[ $(curl -s https://discord.com) ]]; then exit 0; else exit $?; fi"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 5

### Add your discord tokens here to store them in a secret file
### They will also be added as an env var
# secret:
#   GME: XXXXXXXXXXXXXXXXXX
#   BTC: XXXXXXXXXXXXXXXXXX

### Add as many tickers as you want below 
### They will be delivered to the API on container start
configmap:
  enabled: false
  config: |
    #!/usr/bin/env bash
    set -eu

    FREQ="10"
    NICK="true"
    COLOR="true"
    ACTIVITY=""

    curl -X POST \
    "localhost:8080/ticker" \
    -H "Content-Type: application/json" \
    -d "{\"ticker\":\"BTC\", \
      \"name\":\"bitcoin\", \
      \"discord_bot_token\":\"${BTC}\", \
      \"crypto\":true, \
      \"frequency\":${FREQ}, \
      \"set_nickname\":${NICK}, \
      \"set_color\":${COLOR}, \
      \"bitcoin\":false, \
      \"activity\":\"${ACTIVITY}\"}"

    curl -X POST \
    "localhost:8080/ticker" \
    -H "Content-Type: application/json" \
    -d "{\"ticker\":\"GME\", \
      \"name\":\"GME\", \
      \"discord_bot_token\":\"${GME}\", \
      \"frequency\":${FREQ}, \
      \"set_nickname\":${NICK}, \
      \"set_color\":${COLOR}, \
      \"activity\":\"${ACTIVITY}\"}"
