apiVersion: v2
appVersion: "2.3.2"
description: discord stock ticker bot
name: discord-stock-ticker
version: 5.3.1
kubeVersion: ">=1.16.0-0"
keywords:
- bot
- stocks
- crypto
- discord
sources:
- https://github.com/rssnyder/discord-stock-ticker
  https://github.com/jr0dd/charts/discord-stock-ticker
  https://github.com/jr0dd/container-images
icon: https://yt3.ggpht.com/a/AATXAJyg-fbSlEWGUgmsY_0DBQKQThY_Shh_yHGGAQ=s900-c-k-c0xffffffff-no-rj-mo
dependencies:
- name: common
  version: 2.5.1
  repository: https://library-charts.k8s-at-home.com
