image:
  repository: ghcr.io/jr0dd/discord-stock-ticker
  pullPolicy: IfNotPresent
  tag: "v2.5.2"

lifecycle:
  postStart:
    exec:
      command: ["bash", "/app/config.sh"]

controller:
  enabled: true
  replicas: 1

env:
  TZ: "America/New_York"
  #SET_NICKNAME: "1"
  #FREQUENCY: "5"
  #SET_COLOR: "1"
  #FLASH_CHANGE: "1"
  #CRYPTO_NAME: "bitcoin"
  #TICKER: "BTC"
  #DISCORD_BOT_TOKEN: "CHANGEME"
  #PERCENTAGE: "1"
  #ARROWS: "1"
  
envFrom:
- secretRef:
    name: discord-tokens

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 8080
        protocol: HTTP

persistence:
  config:
    enabled: false
    mountPath: /config

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /ticker
        port: 8080

config: |
  #!/usr/bin/env bash
  set -eu
  
  # Just copy and paste the below samples and change 
  # the ticker, name, discord_bot_token values appropriately

  FREQ="6"
  NICK="true"
  COLOR="true"
  FLASH="true"
  PERCENT="true"
  ARROWS="true"

  curl -X POST \
  "localhost:8080/ticker" \
  -H "Content-Type: application/json" \
  -d "{\"ticker\":\"BTC\", \
     \"name\":\"bitcoin\", \
     \"discord_bot_token\":\"${BTC}\", \
     \"crypto\":true, \
     \"frequency\":${FREQ}, \
     \"set_nickname\":${NICK}, \
     \"set_color\":${COLOR}, \
     \"flash_change\":${FLASH}, \
     \"percentage\":${PERCENT}, \
     \"arrows\":${ARROWS}}"

  curl -X POST \
  "localhost:8080/ticker" \
  -H "Content-Type: application/json" \
  -d "{\"ticker\":\"AMC\", \
     \"name\":\"AMC\", \
     \"discord_bot_token\":\"${AMC}\", \
     \"crypto\":false, \
     \"frequency\":${FREQ}, \
     \"set_nickname\":${NICK}, \
     \"set_color\":${COLOR}, \
     \"flash_change\":${FLASH}, \
     \"percentage\":${PERCENT}, \
     \"arrows\":${ARROWS}}"
