image:
  repository: dwinks/pwrstat_docker
  pullPolicy: IfNotPresent
  tag: "latest"

controller:
  enabled: true
  replicas: 1
  strategy: RollingUpdate

env:
  TZ: "America/New_York"

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 5003
        protocol: HTTP

persistence:
  ups:
    enabled: true
    type: hostPath
    hostPath: /dev/bus/usb/003/005
    mountPath: /dev/bus/usb/001/001
    readOnly: false

securityContext:
  privileged: true

ingress:
  main:
    enabled: false

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 5003
  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 5003
  startup:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /health
        port: 5003

config: |
  pwrstat_api:
    log_level: WARNING
  # mqtt:
  #   broker: "192.168.1.100"
  #   port: 1883
  #   client_id: "pwrstat_mqtt"
  #   topic: "sensors/basement/power/ups"
  #   refresh: 30
  #   qos: 0
  #   retained: true
  #   username: "my_username" # optional
  #   password: "my_password" # optional, required if username specified
  rest:
    port: 5003
    bind_address: "0.0.0.0"
  prometheus:
    port: 9222
    bind_address: "0.0.0.0"
    labels:
      rack: "0"
