{{- if .Values.configmap.enabled -}}
apiVersion: v1                                                                                                                                                                                                              
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  payload.sh: |
{{ .Values.configmap.config | indent 4 }}
{{- end -}}