image:
  repository: pihole/pihole
  pullPolicy: IfNotPresent
  tag: "v5.8.1"

controller:
  enabled: true
  replicas: 1
  strategy: RollingUpdate

env:
  TZ: "America/New_York"

service:
  main:
    ports:
      http:
        port: 80
  dns-tcp:
    enabled: true
    type: ClusterIP
    ports:
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
  dns-udp:
    enabled: true
    type: ClusterIP
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP

persistence:
  config:
    enabled: false
    mountPath: /etc/pihole
  dnsmasq:
    enabled: false
    mountPath: /etc/dnsmasq.d

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
