image:
  repository: ghcr.io/linuxserver/wireguard
  pullPolicy: IfNotPresent
  tag: "latest"

controller:
  enabled: true
  replicas: 1

env:
  TZ: "America/New_York"

service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        port: 51820
        protocol: UDP

persistence:
  config:
    enabled: false
    mountPath: /config

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["bash", "-c", "if wg | grep -q wg0 && cat /tmp/healthy == 'live'; then exit 0; fi"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 5

  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["bash", "-c", "if wg | grep -q wg0 && cat /tmp/healthy == 'ready'; then echo 'live' > /tmp/healthy; fi"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3

  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["bash", "-c", "if wg | grep -q wg0; then echo 'ready' > /tmp/healthy; fi"]
      initialDelaySeconds: 5
      timeoutSeconds: 2
      periodSeconds: 10
      failureThreshold: 5

# Use the following site to easily generate configs
# https://www.wireguardconfig.com
config: |
  [Interface]
  Address = 10.0.0.1/28
  ListenPort = 51820
  PrivateKey = ABCDEFGHIJK=
  PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
  
  [Peer]
  PublicKey = ABCDEFGHIJK=
  PresharedKey = ABCDEFGHIJK=
  AllowedIPs = 10.0.0.2/32