image:
  repository: ghcr.io/k8s-at-home/wireguard
  pullPolicy: IfNotPresent
  tag: "v1.0.20210424"

controller:
  enabled: true
  replicas: 1
  strategy: RollingUpdate

env:
  TZ: "America/New_York"
  IPTABLES_BACKEND: "nft"
  KILLSWITCH: "false"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: false
      vpn:
        enabled: true
        port: 51820
        protocol: UDP

securityContext:
  capabilities:
    add:
    - NET_ADMIN
    - SYS_MODULE

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command: ["bash", "-c", "if [[ $(curl -s https://ipinfo.io) ]]; then exit 0; else exit $?; fi"]
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 5
  
  readiness:
     enabled: true
     custom: true
     spec:
       exec:
         command: ["bash", "-c", "if wg | grep -q wg0; then exit 0; else exit $?; fi"]
       initialDelaySeconds: 0
       timeoutSeconds: 1
       periodSeconds: 5
       failureThreshold: 3

   startup:
     enabled: false

# Use the following site to easily generate configs
# https://www.wireguardconfig.com
configSecret:
  enabled: false
  config: |
    # place base64 encoded wg0.conf here
