apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: default
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  CF_ZONE_API_TOKEN: << your zone api token encoded in base64 with `echo -n YOURTOKEN | base4` >>
  CF_DNS_API_TOKEN: << your dns api token that you manually created encoded in base64 with `echo -n YOURTOKEN | base4`  >>
