---
name: "Metadata: Label issues and pull requests"

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
  pull_request_target:
    types:
      - opened
      - edited
      - closed
      - reopened
      - ready_for_review
      - synchronize

jobs:
  label:
    name: Label issues and pull requests
    runs-on: ubuntu-20.04
    steps:
    - uses: Videndum/label-mastermind@2.1.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        configJSON: |
          {
            "releaseMastermind": {
              "labels": {
                "kind:incorrect-title": {
                  "name": "kind:incorrect-title",
                  "colour": "#ffb700",
                  "description": "Incorrect title"
                }
              },
              "runners": [
                {
                  "root": ".",
                  "versioning": {
                    "source": "milestones",
                    "type": "other"
                  },
                  "pr": {
                    "labels": {
                      "kind:incorrect-title": {
                        "requires": 2,
                        "conditions": [
                          {
                            "type": "creatorMatches",
                            "pattern": "^(?!renovate).+"
                          },
                          {
                            "type": "titleMatches",
                            "pattern": "^(?!\\[[a-z0-9\\-]+\\]\\s.+).+"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
