---
name: 'Metadata: Label Commenter'

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Label commenter
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - uses: peaceiris/actions-label-commenter@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
